#Minecraft server properties
#Tue Apr 16 22:46:04 CEST 2024
border-color=-1
caption-color=-1
hide-window-border=false
system-backdrop-type=DWMSBT_TRANSIENTWINDOW
text-color=-1
use-default-border-color=true
use-default-caption-color=true
use-default-text-color=true
use-immersive-dark-mode=true
window-corner-preference=DWMWCP_ROUND
