StartupEvents.registry('item', event => {
    event.create('copper_circuit')
    event.create('blank_circuit')
    event.create('overcharged_diamond')
    event.create('overcharged_gold')
    event.create('overcharged_iron_sheet')
    event.create('overcharged_golden_sheet')
    // AE2 press dies (crafted from press, used as permanent deployer tools)
    event.create('silicon_press_die').maxDamage(32767)
    event.create('calculation_press_die').maxDamage(32767)
    event.create('logic_press_die').maxDamage(32767)
    event.create('engineering_press_die').maxDamage(32767)
    // AE2 press intermediates (ported from createappliedkinetics)
    event.create('incomplete_silicon_press')
    event.create('incomplete_calculation_processor_press')
    event.create('incomplete_logic_processor_press')
    event.create('incomplete_engineering_processor_press')
    // AE2 printed circuit intermediates
    event.create('incomplete_printed_calculation_circuit')
    event.create('incomplete_printed_logic_circuit')
    event.create('incomplete_printed_engineering_circuit')
    event.create('incomplete_silicon_print')
    // AE2 processor intermediates
    event.create('incomplete_logic_processor')
    event.create('incomplete_calculation_processor')
    event.create('incomplete_engineering_processor')
})
