#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Dec 13 14:45:37 CET 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.7.1 + EuphoriaPatches_1.8.6
enableShaders=false
