JEIEvents.hideItems(event => {
    event.hide('mekanism:block_raw_uranium')
    event.hide('biomesoplenty:redwood_log')
    event.hide('biomesoplenty:fir_log')
    event.hide('create_jetpack:jetpack_placeable')
    event.hide('create_jetpack:netherite_jetpack_placeable')
    event.hide('moonlight:placeable_item')
    event.hide('create_connected:incomplete_control_chip')
    event.hide('extra_compat:foul_soup_cup')
    event.hide('extra_compat:cavern_explorer_stew_cup')
    event.hide('extra_compat:miso_with_bamboo_sprouts_cup')
    event.hide('extra_compat:mosquito_repellent_stew_cup')
    event.hide('extra_compat:acacia_blossom_soup_cup')
    event.hide('extra_compat:kangaroo_stew_cup')
    event.hide('wither_spawn_animation:no_w')
    event.hide('cinematiccataclysm:debug_stick')
    event.hide('monolib:debug_block')
    event.hide('monolib:debug_item')
    event.hide('fdlib:test_multiblock')
    event.hide('alexsmobsinteraction:eggs')
    event.hide('ae2:facade')

    // event.hide('cataclysm:stone_tiles')
    // event.hide('cataclysm:stone_tile_slab')
    // event.hide('cataclysm:stone_tile_stairs')
    // event.hide('cataclysm:stone_tile_wall')

    event.hide(/minecraft:.*sapling.*/)
    event.hide(/biomesoplenty:.*sapling.*/)
    event.hide(/natures_spirit:.*sapling.*/)
    event.hide(/autumnity:.*sapling.*/)
    event.hide(/quark:.*sapling.*/)
    event.hide(/aether:.*sapling.*/)
    event.hide(/deep_aether:.*sapling.*/)
    event.hide(/aether_redux:.*sapling.*/)
    event.hide(/ancient_aether:.*sapling.*/)
    event.hide(/upgrade_aquatic:.*sapling.*/)
    event.hide(/minecraft:.*propagule.*/)
    event.hide(/xaeroworldmap:.*/)
    event.hide(/xaerominimap:.*/)
    event.hide(/citadel:.*/)
    event.hide(/structure_gel:.*/)
    event.hide(/dragonlib:.*/)
})
