	#model x1/x2 = LOD x
			
	nbt.2.ProfessionName=raw:iregex:(.*Merchant.*)
	models.2=30
	distanceFromPlayer.2=0-12
	
	nbt.3.ProfessionName=raw:iregex:(.*Merchant.*)
	models.3=31
	distanceFromPlayer.3=12-32
	
	nbt.4.ProfessionName=raw:iregex:(.*Merchant.*)
	models.4=32




	models.5=20
	distanceFromPlayer.5=0-12
	
	models.6=21
	distanceFromPlayer.6=12-32
	
	models.7=22