modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = ""

[[mods]]
modId = "relicskeybind"
version = "1.0.0"
displayName = "Relics Keybind"
description = '''
Changes the Relics mod research key from Shift to W.
'''

[[dependencies.relicskeybind]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.relicskeybind]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.relicskeybind]]
modId = "relics"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "mixins.relicskeybind.json"
