modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[dependencies.mekanismfix]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.mekanismfix]]
    modId="mekanism"
    mandatory=true
    versionRange="[10.4,)"
    ordering="AFTER"
    side="CLIENT"

[[mods]]
modId="mekanismfix"
version="1.0.1"
displayName="Mekanism Embeddium Fix"
description="Fixes Mekanism cables rendering as disconnected with Embeddium/Xenon by calling requestModelDataUpdate() on load."
