	#model x1/x2 = LOD x
			### LOD x2 broken for mobs using layers of textures. Using the original guard instead
	
	#model 90 = better combat compat

	models.2=20
	#distanceFromPlayer.2=0-12
	
	#models.3=21
	#distanceFromPlayer.3=12-32
	
	#models.4=1